/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fooddeliverysystem;

import java.awt.Color;

/**
 *
 * @author inn
 */
public class customerMenu extends javax.swing.JPanel {

    /**
     * Creates new form customerMenu
     */
    public customerMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foodDeliveyPanel = new javax.swing.JPanel();
        headingLabel = new javax.swing.JLabel();
        subheadingLabel = new javax.swing.JLabel();
        orderNowButton = new javax.swing.JButton();
        imageHolder = new javax.swing.JLabel();
        pickUpPanel = new javax.swing.JPanel();
        pickUpHeading = new javax.swing.JLabel();
        subHeadinglabel = new javax.swing.JLabel();
        pickUpImageHolder = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        groceryLabel = new javax.swing.JLabel();
        subHeading = new javax.swing.JLabel();
        shopsImageHolder = new javax.swing.JLabel();
        mainHeading = new javax.swing.JLabel();
        headImageHolder = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foodDeliveyPanel.setBackground(new java.awt.Color(102, 255, 102));

        headingLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        headingLabel.setText(" Food Delivery");

        subheadingLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        subheadingLabel.setText("Let's get some FOOD!");

        orderNowButton.setBackground(new java.awt.Color(204, 204, 204));
        orderNowButton.setText("Order Now!");
        orderNowButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                orderNowButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                orderNowButtonMouseExited(evt);
            }
        });

        imageHolder.setBackground(new java.awt.Color(102, 255, 102));
        imageHolder.setForeground(new java.awt.Color(102, 255, 102));
        imageHolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sixthPhotoEdit.png"))); // NOI18N

        javax.swing.GroupLayout foodDeliveyPanelLayout = new javax.swing.GroupLayout(foodDeliveyPanel);
        foodDeliveyPanel.setLayout(foodDeliveyPanelLayout);
        foodDeliveyPanelLayout.setHorizontalGroup(
            foodDeliveyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodDeliveyPanelLayout.createSequentialGroup()
                .addGroup(foodDeliveyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(foodDeliveyPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(headingLabel))
                    .addGroup(foodDeliveyPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(foodDeliveyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subheadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderNowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(imageHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        foodDeliveyPanelLayout.setVerticalGroup(
            foodDeliveyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodDeliveyPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(foodDeliveyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imageHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(foodDeliveyPanelLayout.createSequentialGroup()
                        .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subheadingLabel)
                        .addGap(26, 26, 26)
                        .addComponent(orderNowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        add(foodDeliveyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 141, -1, -1));

        pickUpPanel.setBackground(new java.awt.Color(51, 255, 51));

        pickUpHeading.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        pickUpHeading.setText("PICK UP!");

        subHeadinglabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        subHeadinglabel.setText("There are discounts available");

        pickUpImageHolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seventhPhotoEdit.jpg"))); // NOI18N

        javax.swing.GroupLayout pickUpPanelLayout = new javax.swing.GroupLayout(pickUpPanel);
        pickUpPanel.setLayout(pickUpPanelLayout);
        pickUpPanelLayout.setHorizontalGroup(
            pickUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pickUpPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pickUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pickUpHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subHeadinglabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pickUpPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pickUpImageHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pickUpPanelLayout.setVerticalGroup(
            pickUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pickUpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pickUpImageHolder, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pickUpHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subHeadinglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(pickUpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 350, -1, 230));

        jPanel1.setBackground(new java.awt.Color(0, 255, 102));

        groceryLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        groceryLabel.setText("Shops");

        subHeading.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        subHeading.setText("Grocery and more...");

        shopsImageHolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NinethPhotoEdit.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(groceryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subHeading, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shopsImageHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shopsImageHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(groceryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(subHeading))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 350, 305, 230));

        mainHeading.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        mainHeading.setForeground(new java.awt.Color(255, 255, 255));
        mainHeading.setText("WELCOME User");
        add(mainHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 290, 60));

        headImageHolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FifthPhotoEdit.jpg"))); // NOI18N
        add(headImageHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 830, 530));
    }// </editor-fold>//GEN-END:initComponents

    private void orderNowButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderNowButtonMouseEntered
        // TODO add your handling code here:
        orderNowButton.setBackground(Color.blue);
    }//GEN-LAST:event_orderNowButtonMouseEntered

    private void orderNowButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderNowButtonMouseExited
        // TODO add your handling code here:
        orderNowButton.setBackground(Color.lightGray);
    }//GEN-LAST:event_orderNowButtonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel foodDeliveyPanel;
    private javax.swing.JLabel groceryLabel;
    private javax.swing.JLabel headImageHolder;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JLabel imageHolder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mainHeading;
    private javax.swing.JButton orderNowButton;
    private javax.swing.JLabel pickUpHeading;
    private javax.swing.JLabel pickUpImageHolder;
    private javax.swing.JPanel pickUpPanel;
    private javax.swing.JLabel shopsImageHolder;
    private javax.swing.JLabel subHeading;
    private javax.swing.JLabel subHeadinglabel;
    private javax.swing.JLabel subheadingLabel;
    // End of variables declaration//GEN-END:variables
}
