/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fooddeliverysystem;

/**
 *
 * @author inn
 */
public class foodDeliveryMenu extends javax.swing.JPanel {

    /**
     * Creates new form foodDeliveryMenu
     */
    public foodDeliveryMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingLabel = new javax.swing.JLabel();
        subheadingLabel = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        foodButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 255, 0));
        setMinimumSize(new java.awt.Dimension(1300, 700));
        setPreferredSize(new java.awt.Dimension(1300, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headingLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 66)); // NOI18N
        headingLabel.setForeground(new java.awt.Color(255, 255, 255));
        headingLabel.setText("FOOD DELIVERY SECTION");
        add(headingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 0, 895, 117));

        subheadingLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        subheadingLabel.setText("It takes a dozen of minutes for food to reach your DOOR!");
        add(subheadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 1050, 84));

        searchTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchTextField.setText("Search");
        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });
        add(searchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 565, -1));

        okButton.setText("GO");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 220, 70, 37));

        foodButton.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        foodButton.setText("Food");
        add(foodButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 313, 293));

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jButton2.setText("OUTLETS");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, 331, 293));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eleventPhotoEdit.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_okButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton foodButton;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JLabel subheadingLabel;
    // End of variables declaration//GEN-END:variables
}
