/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fooddeliverysystem;

/**
 *
 * @author inn
 */
public class foodSelection extends javax.swing.JPanel {

    /**
     * Creates new form foodSelectionm
     */
    public foodSelection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingPanel = new javax.swing.JPanel();
        headingLabel = new javax.swing.JLabel();
        subHeadingPanel = new javax.swing.JPanel();
        subheadingLabel = new javax.swing.JLabel();
        foodInformationPanel = new javax.swing.JPanel();
        foodInformationLabel = new javax.swing.JLabel();
        foodInformationPanel1 = new javax.swing.JPanel();
        foodInformationLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        mainImageHolder = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1300, 700));
        setPreferredSize(new java.awt.Dimension(1300, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headingLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 48)); // NOI18N
        headingLabel.setText("DEAR USER,");

        javax.swing.GroupLayout headingPanelLayout = new javax.swing.GroupLayout(headingPanel);
        headingPanel.setLayout(headingPanelLayout);
        headingPanelLayout.setHorizontalGroup(
            headingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headingPanelLayout.setVerticalGroup(
            headingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headingPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headingLabel)
                .addGap(43, 43, 43))
        );

        add(headingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 320, 80));

        subheadingLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        subheadingLabel.setText("Here are the food items you can order!");

        javax.swing.GroupLayout subHeadingPanelLayout = new javax.swing.GroupLayout(subHeadingPanel);
        subHeadingPanel.setLayout(subHeadingPanelLayout);
        subHeadingPanelLayout.setHorizontalGroup(
            subHeadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subHeadingPanelLayout.createSequentialGroup()
                .addComponent(subheadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        subHeadingPanelLayout.setVerticalGroup(
            subHeadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subHeadingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subheadingLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(subHeadingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 480, 50));

        foodInformationLabel.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        foodInformationLabel.setText("FOOD RESTUARANT PRICE");

        javax.swing.GroupLayout foodInformationPanelLayout = new javax.swing.GroupLayout(foodInformationPanel);
        foodInformationPanel.setLayout(foodInformationPanelLayout);
        foodInformationPanelLayout.setHorizontalGroup(
            foodInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(foodInformationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        foodInformationPanelLayout.setVerticalGroup(
            foodInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(foodInformationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        add(foodInformationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 470, -1));

        foodInformationLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        foodInformationLabel1.setText("FOOD RESTUARANT PRICE");

        javax.swing.GroupLayout foodInformationPanel1Layout = new javax.swing.GroupLayout(foodInformationPanel1);
        foodInformationPanel1.setLayout(foodInformationPanel1Layout);
        foodInformationPanel1Layout.setHorizontalGroup(
            foodInformationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(foodInformationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(foodInformationPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(foodInformationLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        foodInformationPanel1Layout.setVerticalGroup(
            foodInformationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
            .addGroup(foodInformationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(foodInformationPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(foodInformationLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        add(foodInformationPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 470, -1));

        jButton1.setText("Rate and Review");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, 120, 40));

        jButton2.setText("ADD TO CART");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 310, 130, 40));

        jButton3.setText("BUY");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 310, 90, 40));

        jButton4.setText("ADD TO CART");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 470, 130, 40));

        jButton5.setText("Rate and Review");
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, 120, 40));

        jButton6.setText("BUY");
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 470, 90, 40));

        mainImageHolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FourthPhotoEdit.jpg"))); // NOI18N
        mainImageHolder.setMinimumSize(new java.awt.Dimension(1300, 700));
        add(mainImageHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 1290, 700));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel foodInformationLabel;
    private javax.swing.JLabel foodInformationLabel1;
    private javax.swing.JPanel foodInformationPanel;
    private javax.swing.JPanel foodInformationPanel1;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JPanel headingPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel mainImageHolder;
    private javax.swing.JPanel subHeadingPanel;
    private javax.swing.JLabel subheadingLabel;
    // End of variables declaration//GEN-END:variables
}
