/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and ope    @Override
    public int getTransparency() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    @Override
    public int getTransparency() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
n the template in the editor.
 */
package fooddeliverysystem;

/**
 *
 * @author Syed Muattar Mehdi Zaidi
 * @author Hussain Shahzad
 */
public class SignIn extends javax.swing.JPanel {

    /**
     * Creates new form SignIn
     */
    
    
    public void login(){
        System.out.print(jComboBox1.getSelectedIndex());
       switch(jComboBox1.getSelectedIndex()){
           case 0:
               
               AdminMenu am=new AdminMenu();
               startForm.getInstance().goTo(am);
               break;
           case 1:
               break;
           case 2:
               EmployeeMenu em=new EmployeeMenu();
               startForm.getInstance().goTo(em);
               break;
           case 3:
               customerMenu cm=new customerMenu();
             
               startForm.getInstance().goTo(cm);
               break;
       }
    
    }
    
    public SignIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingLabel = new javax.swing.JLabel();
        UsernameInput = new javax.swing.JTextField();
        passwordInput = new javax.swing.JTextField();
        signInButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        imageHolder = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headingLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 60)); // NOI18N
        headingLabel.setForeground(new java.awt.Color(255, 255, 255));
        headingLabel.setText("SIGN IN");
        add(headingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        UsernameInput.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        UsernameInput.setText("Username");
        add(UsernameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 420, 40));

        passwordInput.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        passwordInput.setText("Password");
        add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 420, 40));

        signInButton.setBackground(new java.awt.Color(46, 146, 46));
        signInButton.setForeground(new java.awt.Color(255, 255, 255));
        signInButton.setText("LOG IN");
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });
        add(signInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 420, 30));

        backButton.setBackground(new java.awt.Color(46, 146, 46));
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 463, 110, 30));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Seller", "Employee", "Customer" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 420, 40));

        imageHolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FirstPhotoEdit.jpg"))); // NOI18N
        add(imageHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        WelcomePage p=new WelcomePage();
        startForm.getInstance().goTo(p);
    }//GEN-LAST:event_backButtonActionPerformed

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_signInButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField UsernameInput;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JLabel imageHolder;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JTextField passwordInput;
    private javax.swing.JButton signInButton;
    // End of variables declaration//GEN-END:variables
}
